name: Unit tests

on: [push]

jobs:
  Unit-tests:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements_dev.txt
          python -m spacy download en_core_web_md
      - name: set up PYTHONPATH
        run: |
          export PYTHONPATH=$PWD
      - name: Unit tests
        run: |
          python -m pytest --cov goodai/tests/unit/
